### ISSUE TITLE
Syncronous Parrot?

### ISSUE THREAD

**Issue by shelldandy** [matheuss/parrotsay-api#1]
I'd like to use this parrot as a goodbye part on a small yeoman thing im doing, but since its async the program exits before the parrot is done loading

Can we have some sort of sync version of the parrot?

Thanks a lot ❤️

**Comment by shelldandy** [comment]
I did a fork which works sync ha

https://www.npmjs.com/package/sync-parrot-api

**Comment by FutureArchitect-wang2449** [comment]
I also prefer the sync version, personallly.

**Comment by iansu** [comment]
@shelldandy This is great. Can you also share the code on GitHub?

**Comment by shelldandy** [comment]
is _probably_ on my repos somewhere...
